### ISSUE TITLE
Could you delete this repo?

### ISSUE THREAD

**Issue by metadaddy** [CoreLayer/CoreLayerADC#1]
It pops up in a search for `corelayer adc` and is a bit confusing :-)

**Comment by jantytgat** [comment]
Hi Pat,


This would require me moving all the contents of this repo (and dependencies) to another one, and there are quite a bit as this repo contains the code for the next-gen version of CoreLogic...

Could you tell me why it is confusing, after all this is a repository for CoreLayer and it is related to Citrix ADC... :-)

**Comment by metadaddy** [comment]
The master branch looks like an abandoned project, but I just realized the substance is in a couple of branches. Maybe make that more clear?

![image](https://user-images.githubusercontent.com/723517/100902269-95921c80-3479-11eb-8377-6960ef689b5e.png)

**Comment by jantytgat** [comment]
I've added some comments to describe the current state of this repo.
Now let's hope to get this new version ready by the next #CitrixConverge event ;-)

**Comment by metadaddy** [comment]
👍
